#!/bin/env bash

USERNAME="efx"

usage() {
	echo "Usage:"
	echo "Example: $0 -d ~/xyz -n abc -e 2"
	echo "	-d <project_folder> required"
	echo "	-n <project_name>"
	echo "		optional, if not given, project folder name is used"
	echo "	-e <efinity_version>"
	echo "	 	1: 2023.1 default"
	echo "	 	2: 2023.2"
	echo "		optional, if not given, 2023.1 is used"
	echo "	-h <help>"
	exit 1
}

while getopts "d:n:e:h" opt; do
	case $opt in
		d)
			PROJECT_FOLDER=$(realpath $OPTARG)
			;;
		n)
			PROJECT_NAME=$OPTARG
			;;
		e)
			EFINITY_VERSION=$OPTARG
			;;
		h)
			usage
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			usage
			;;
	esac
done

# check if project folder is given
if [ -z "$PROJECT_FOLDER" ]; then
	echo "Project folder not given"
	usage
fi

# check if project name is given
if [ -z "$PROJECT_NAME" ]; then
	PROJECT_NAME=$(basename "$PROJECT_FOLDER")
fi

# check if efinity version is given
if [ -z "$EFINITY_VERSION" ]; then
	EFINITY_VERSION=1
fi

SERVER_IP="galactos.local"
SERVER_PROJECT_FOLDER="/home/$USERNAME/hdd/efinity_company_projects"

ssh-keygen -F $SERVER_IP > /dev/null
ID_ALREADY_PRESENT=$?

if [[ $ID_ALREADY_PRESENT -ne 0 ]]; then
	ssh-copy-id $USERNAME@$SERVER_IP
fi

ZIP_FILE=$(efx_parse "$PROJECT_FOLDER/$PROJECT_NAME.xml")
echo "$ZIP_FILE"

scp $ZIP_FILE $USERNAME@$SERVER_IP:"$SERVER_PROJECT_FOLDER"
if [ $? -ne 0 ]; then
	echo "Error in copying file to server"
	exit 1
fi

rm "$ZIP_FILE"

ID=$(echo $RANDOM | md5sum | head -c 10)
echo $ID

ssh $USERNAME@$SERVER_IP "efx_ser $SERVER_PROJECT_FOLDER/$ZIP_FILE $PROJECT_NAME $EFINITY_VERSION $ID"

scp $USERNAME@$SERVER_IP:"$SERVER_PROJECT_FOLDER/$ID/outflow.zip" .

unzip -o outflow.zip -d "$PROJECT_FOLDER" 

ssh $USERNAME@$SERVER_IP "rm -r $SERVER_PROJECT_FOLDER/$ID"

rm outflow.zip
