#!/bin/env bash

USERNAME="efx"

usage() {
	echo -e "Usage:"
	echo -e "Example: $0 -d ~/xyz -n abc -e 2"
	echo -e " -d <project_folder> required"
	echo -e " -n <project_name>"
	echo -e "\toptional, if not given, project folder name is used"
	echo -e " -e <efinity_version>"
	echo -e "\t2023.1"
	echo -e "\t2023.2 (default)"
	echo -e "\t2024.1"
  echo -e "\t2024.2"
	echo -e "\toptional, if not given, 2023.2 is used"
	echo -e " -o <outflow dir>"
	echo -e "\toptional, specify an alternative outflow directory"
	echo -e " -h <help>"
	exit 1
}

while getopts "d:n:e:ho:" opt; do
	case $opt in
		d)
			PROJECT_FOLDER=$(realpath $OPTARG)
			;;
		n)
			PROJECT_NAME=$OPTARG
			;;
		e)
			EFINITY_VERSION=$OPTARG
			;;
		h)
			usage
			;;
		o)
			OUTFLOW_OUT_DIR="$OPTARG"
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			usage
			;;
	esac
done

# check if project folder is given
if [ -z "$PROJECT_FOLDER" ]; then
	echo "Project folder not given"
	usage
fi

# check if project name is given
if [ -z "$PROJECT_NAME" ]; then
	PROJECT_NAME=$(basename "$PROJECT_FOLDER")
fi

# check if efinity version is given
if [ -z "$EFINITY_VERSION" ]; then
	EFINITY_VERSION=2023.2
fi

if [ -z "$OUTFLOW_OUT_DIR" ]; then
	OUTFLOW_OUT_DIR="$PROJECT_FOLDER"
else
	OUTFLOW_OUT_DIR="$PROJECT_FOLDER"/"$OUTFLOW_OUT_DIR"
fi

SERVER_IP="galactos.local"
SERVER_PROJECT_FOLDER="/home/$USERNAME/hdd/efinity_company_projects"

ssh-keygen -F $SERVER_IP > /dev/null
ID_ALREADY_PRESENT=$?

if [[ $ID_ALREADY_PRESENT -ne 0 ]]; then
	ssh-copy-id $USERNAME@$SERVER_IP
fi

ZIP_FILE=$(efx_parse "$PROJECT_FOLDER/$PROJECT_NAME.xml")
echo "$0 zip file $ZIP_FILE"

scp $ZIP_FILE $USERNAME@$SERVER_IP:"$SERVER_PROJECT_FOLDER"
if [ $? -ne 0 ]; then
	echo "Error in copying file to server"
	exit 1
fi

rm "$ZIP_FILE"

ID=$(echo $RANDOM | md5sum | head -c 10)
echo "$0 ID assigned $ID"

echo "$0 Dumping outflow in $OUTFLOW_OUT_DIR"
echo "$0 Selected Efinity version $EFINITY_VERSION"

ssh $USERNAME@$SERVER_IP "efx_ser $SERVER_PROJECT_FOLDER/$ZIP_FILE $PROJECT_NAME $EFINITY_VERSION $ID"

if (( $? != 0 )); then
  echo "$0 Failed running efx_ser; Exit Status is $?"
  exit 1
fi

scp $USERNAME@$SERVER_IP:"$SERVER_PROJECT_FOLDER/$ID/outflow.zip" .

if (( $? != 0 )); then
  echo "$0 Failed copying outflow.zip from server to local machine; Exit Status is $?"
  echo "Try running these commands to copy it manually:"
  echo "scp $USERNAME@$SERVER_IP:"$SERVER_PROJECT_FOLDER/$ID/outflow.zip" ."
  echo "unzip -o outflow.zip -d "$OUTFLOW_OUT_DIR""
  echo "ssh $USERNAME@$SERVER_IP "rm -r $SERVER_PROJECT_FOLDER/$ID""
  exit 1
fi

unzip -o outflow.zip -d "$OUTFLOW_OUT_DIR"

ssh $USERNAME@$SERVER_IP "rm -r $SERVER_PROJECT_FOLDER/$ID"

if (( $? != 0 )); then
  echo "$0 Failed to remove outflow.zip from remote machine; Exit Status is $?"
  exit 1
fi

rm outflow.zip
