#!/bin/env sh
# HOME="/home/dj"
BASE_FOLDER="${HOME}/hdd/efinity_company_projects"

cd $BASE_FOLDER || exit

ZIP_FILE="$1"
# PROJECT_FOLDER=$(basename -s ".zip" ${ZIP_FILE})
PROJECT_FOLDER="$4"

echo ${PROJECT_FOLDER}

mkdir ${PROJECT_FOLDER}
cd ${PROJECT_FOLDER}

CURRENT_PATH=$(pwd)

unzip ${ZIP_FILE}
if [ $? -ne 0 ]; then
	echo "Unzip failed"
	exit 1
fi

rm ${ZIP_FILE}

PROJECT_NAME="$2"
EFINITY_HOME="${HOME}/hdd/shreeyash/efinity/2023.$3"
PYTHON_PATH="${EFINITY_HOME}/bin"

sed -i "s|location=\"[^\"]*\"|location=\"${CURRENT_PATH}\"|" ${PROJECT_NAME}.xml

export EFINITY_HOME="${EFINITY_HOME}"
export PATH=${PYTHON_PATH}:$(echo $PATH)
export EFXPT_HOME="${EFINITY_HOME}/pt"
export EFXPGM_HOME="${EFINITY_HOME}/pgm"

echo "Running Synthesis"
${EFINITY_HOME}/scripts/efx_run.py ${PROJECT_NAME}.xml
# ${EFINITY_HOME}/scripts/efx_run.py -f pgm ${PROJECT_NAME}.xml

zip -r -9 outflow.zip outflow

# Print a brief summary before sending the files

awk '/Resource Summary \(begin\)/{p=1} { if (p == 1) { print $0 }} /Resource Summary \(end\)/{p=0}' $BASE_FOLDER/$PROJECT_FOLDER/outflow/$PROJECT_NAME.place.rpt
awk '/Clock Frequency Summary \(begin\)/{p=1} { if (p == 1) { print $0 }} /Clock Frequency Summary \(end\)/{p=0}' $BASE_FOLDER/$PROJECT_FOLDER/outflow/$PROJECT_NAME.timing.rpt
awk '/Clock Relationship Summary \(begin\)/{q=1} { if (q == 1) { print $0 }} /Clock Relationship Summary \(end\)/{q=0}'  $BASE_FOLDER/$PROJECT_FOLDER/outflow/$PROJECT_NAME.timing.rpt
